(()=>{
 const obs=(window.OBSERVATIONS||[]).filter(o=>o.public!==false).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const timeline=document.querySelector('#walkTimeline'),cal=document.querySelector('#walkCalendar');
 const monthFmt=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}),dateFmt=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'});
 const groups={};obs.forEach(o=>{const d=new Date((o.date||'')+'T12:00:00');const key=isNaN(d)?'Undated':monthFmt.format(d);(groups[key]??=[]).push(o)});
 const card=o=>{const photos=o.photos||[],shown=photos.slice(0,8);return `<article class="journal-entry" id="walk-${o.id}"><a class="journal-entry-link" href="observation.html?id=${encodeURIComponent(o.id)}"><div class="eyebrow">${o.date?dateFmt.format(new Date(o.date+'T12:00:00')):''}</div><h3>${o.title||'A garden walk'}</h3></a><p>${o.notes||'A moment preserved from the garden.'}</p>${shown.length?`<div class="compact-gallery" data-gallery-title="${String(o.title||'Garden Walk').replace(/"/g,'&quot;')}">${shown.map((src,i)=>`<button type="button" class="gallery-thumb" data-gallery-src="${src}"><img src="${src}" alt="${o.title||'Garden Walk'} photo ${i+1}" loading="lazy">${i===7&&photos.length>8?`<span class="more-overlay">+${photos.length-8}</span>`:''}</button>`).join('')}</div>`:''}<div class="chips"><a class="chip chip-link" href="observation.html?id=${encodeURIComponent(o.id)}">Open this memory →</a></div></article>`};
 timeline.innerHTML=Object.entries(groups).map(([m,items])=>`<section class="panel"><h2>${m}</h2>${items.map(card).join('')}</section>`).join('')||'<div class="panel"><p>No published Garden Walks yet.</p></div>';
 const toggle=document.querySelector('#calendarToggle');if(toggle)toggle.onclick=()=>{cal.hidden=!cal.hidden;timeline.hidden=!timeline.hidden;toggle.textContent=cal.hidden?'Calendar view':'Timeline view';if(!cal.hidden){const days={};obs.forEach(o=>(days[o.date]??=[]).push(o));cal.innerHTML=`<div class="panel"><h2>Calendar</h2>${Object.entries(days).map(([d,items])=>`<p><strong>${dateFmt.format(new Date(d+'T12:00:00'))}</strong> · ${items.map(x=>`<a href="observation.html?id=${encodeURIComponent(x.id)}">${x.title||'Garden Walk'}</a>`).join(' • ')}</p>`).join('')}</div>`}};
 if(window.HOMEPAGE_WEEKLY_STORY){const w=window.HOMEPAGE_WEEKLY_STORY;document.querySelector('#walkWeeklyTitle').textContent=w.title||'This week in the garden';document.querySelector('#walkWeeklySummary').textContent=w.summary||''}
})();
