(()=>{
 const obs=window.OBSERVATIONS||[], plants=window.PLANTS||[], objects=window.GARDEN_BRAIN?.objects||[];
 const now=new Date(), days=d=>Math.max(0,Math.floor((now-new Date(d+'T12:00:00'))/864e5));
 const hasPortrait=p=>Boolean(window.IMAGE_MANIFEST?.plants?.[p.number]?.hero || (p.image && !/placeholder|coming/i.test(p.image)) || obs.some(o=>o.primary?.kind==='plant'&&Number(o.primary.id)===Number(p.number)&&o.setHero&&(o.photos||[]).length));
 const lastPlant=n=>obs.filter(o=>(o.plants||[]).map(Number).includes(Number(n))).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];
 const lastObject=id=>obs.filter(o=>(o.objects||[]).includes(id)).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];
 const dismissed=new Set(JSON.parse(localStorage.getItem('gardenBrainDismissedTasks')||'[]'));
 let tasks=[];
 plants.forEach(p=>{if(!hasPortrait(p))tasks.push({id:`portrait-${p.number}`,type:'portrait',score:100,text:`${p.common} (#${p.number}) still needs a master portrait.`,href:`field-notebook.html?kind=plant&id=${p.number}`});const l=lastPlant(p.number);if(!l)tasks.push({id:`observe-${p.number}`,type:'observation',score:70,text:`No dated Garden Walk update exists yet for ${p.common}.`,href:`field-notebook.html?kind=plant&id=${p.number}`});else if(days(l.date)>30)tasks.push({id:`stale-${p.number}`,type:'observation',score:days(l.date),text:`${p.common} has not been updated in ${days(l.date)} days.`,href:`field-notebook.html?kind=plant&id=${p.number}`})});
 objects.forEach(o=>{const l=lastObject(o.id);if(!l)tasks.push({id:`place-${o.id}`,type:'place',score:65,text:`${o.name} has no linked Garden Walk yet.`,href:`field-notebook.html?kind=object&id=${o.id}`})});
 tasks=tasks.filter(t=>!dismissed.has(t.id)).sort((a,b)=>b.score-a.score);
 const list=document.querySelector('#allTasks'), count=document.querySelector('#taskCount'), search=document.querySelector('#taskSearch'), filter=document.querySelector('#taskFilter');
 function render(){const q=search.value.trim().toLowerCase(), f=filter.value;const shown=tasks.filter(t=>(f==='all'||t.type===f)&&(!q||t.text.toLowerCase().includes(q)));count.textContent=`${shown.length} gentle reminder${shown.length===1?'':'s'}`;list.innerHTML=shown.map(t=>`<div class="task-row"><a class="prompt" href="${t.href}"><span>→</span><span>${t.text}</span></a><button type="button" data-dismiss="${t.id}" aria-label="Dismiss task">Dismiss</button></div>`).join('')||'<div class="prompt">Everything current. Go enjoy the garden. 💚</div>';list.querySelectorAll('[data-dismiss]').forEach(b=>b.addEventListener('click',()=>{dismissed.add(b.dataset.dismiss);localStorage.setItem('gardenBrainDismissedTasks',JSON.stringify([...dismissed]));tasks=tasks.filter(t=>t.id!==b.dataset.dismiss);render()}));}
 search.addEventListener('input',render);filter.addEventListener('change',render);render();
})();