(()=>{
  'use strict';
  const $=selector=>document.querySelector(selector),cfg=window.FIELD_NOTEBOOK_CONFIG||{},contractPromise=import('./domain/foundation-write-contract.mjs');
  let species=structuredClone(window.GARDEN_SPECIES||[]),observations=window.OBSERVATIONS||[],residents=window.GARDEN_RESIDENTS||[],selected='',remoteRevision='';
  const e={key:$('#key'),status:$('#status'),list:$('#speciesList'),search:$('#search'),form:$('#editForm'),title:$('#editorTitle'),name:$('#name'),scientific:$('#scientificName'),rank:$('#rank'),confidence:$('#confidence'),parent:$('#parentSpeciesId'),category:$('#category'),aliases:$('#aliases'),note:$('#identificationNote'),history:$('#history'),source:$('#mergeSource'),target:$('#mergeTarget'),preview:$('#mergePreview')};
  e.key.value=localStorage.getItem('gardenBrainKey')||'';e.key.oninput=()=>localStorage.setItem('gardenBrainKey',e.key.value);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const active=()=>species.filter(record=>!record.mergedInto);
  function status(text,bad=false){e.status.textContent=text;e.status.style.background=bad?'#f9e7e2':'#eef3eb'}
  async function api(path,options={}){if(!e.key.value)throw Error('Enter your Garden Brain key first.');const response=await fetch(cfg.apiUrl.replace(/\/$/,'')+path,{...options,headers:{authorization:'Bearer '+e.key.value,'content-type':'application/json',...(options.headers||{})},cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error||'Request failed ('+response.status+').');return body}
  function counts(id){let obs=0,photos=0,res=0;for(const observation of observations){const ids=new Set([...(observation.species||[]),...(observation.visitorDetails||[]).map(detail=>detail.speciesId)].filter(Boolean));if(ids.has(id)){obs++;photos+=(observation.photos||[]).length}}res=residents.filter(record=>record.speciesId===id).length;return{obs,photos,res}}
  function fillSelects(){const options=active().map(record=>'<option value="'+esc(record.id)+'">'+esc(record.name)+' — '+esc(record.scientificName||record.rank||'')+'</option>').join('');e.parent.innerHTML='<option value="">No parent / broadest level</option>'+options;e.source.innerHTML='<option value="">Choose duplicate</option>'+options;e.target.innerHTML='<option value="">Choose survivor</option>'+options;e.preview.textContent='Taxonomy merges are blocked during Foundation staging acceptance.'}
  function render(){const query=e.search.value.trim().toLowerCase();e.list.innerHTML=species.filter(record=>!query||[record.name,record.scientificName,...(record.aliases||[])].join(' ').toLowerCase().includes(query)).map(record=>'<button type="button" class="species-row '+(record.id===selected?'active ':'')+(record.mergedInto?'merged':'')+'" data-id="'+esc(record.id)+'"><span><strong>'+esc(record.icon||'🐾')+' '+esc(record.name)+'</strong><br><small>'+esc(record.scientificName||'Unresolved')+' · '+esc(record.rank||'')+'</small></span><small>'+(record.id.startsWith('stg-')?'staging':'baseline · read-only')+'</small></button>').join('');e.list.querySelectorAll('button').forEach(button=>button.onclick=()=>load(button.dataset.id));fillSelects()}
  function load(id){const record=species.find(candidate=>candidate.id===id);if(!record)return;selected=id;e.title.textContent=(id.startsWith('stg-')?'Edit ':'Review ')+record.name;e.name.value=record.name||'';e.scientific.value=record.scientificName||'';e.rank.value=[...e.rank.options].some(option=>option.value===record.rank)?record.rank:'useful group';e.confidence.value=[...e.confidence.options].some(option=>option.value===record.identification?.confidence)?record.identification.confidence:'tentative';e.parent.value=record.parentSpeciesId||'';e.category.value=record.category||'';e.aliases.value=(record.aliases||[]).join(', ');e.note.value='';e.history.innerHTML=(record.identification?.history||[]).slice().reverse().map(item=>'<article><strong>'+esc(item.label||record.name)+'</strong> · '+esc(item.scientificName||'')+'<br><small>'+esc(item.rank||'')+' · '+esc(item.confidence||'')+' · '+esc(item.source||'Unknown source')+' · '+esc((item.at||'').slice(0,10))+'</small>'+(item.note?'<p>'+esc(item.note)+'</p>':'')+'</article>').join('')||'<p class="muted">No history yet.</p>';render();status(id.startsWith('stg-')?'Staging taxonomy record is editable.':'Foundation taxonomy is immutable during acceptance testing.')}
  async function refresh(){status('Refreshing from the staging Worker…');const body=await api('/garden');species=body.species||[];observations=body.observations||[];residents=body.residents||[];remoteRevision=body.revision||'';if(!remoteRevision)throw Error('No staging data revision was returned.');render();status('Loaded the isolated staging data branch.')}
  async function refine(event){event.preventDefault();if(!selected)throw Error('Choose a taxonomy record first.');if(!selected.startsWith('stg-'))throw Error('Foundation baseline taxonomy is read-only during staging acceptance.');if(!remoteRevision)await refresh();const contract=await contractPromise,body=contract.withRevision({speciesId:selected,name:e.name.value.trim(),scientificName:e.scientific.value.trim(),rank:e.rank.value,confidence:e.confidence.value,parentSpeciesId:e.parent.value||null,category:e.category.value.trim(),aliases:e.aliases.value.split(',').map(value=>value.trim()).filter(Boolean),note:e.note.value.trim(),source:'Human-reviewed staging taxonomy acceptance'},remoteRevision);status('Saving staging refinement…');const result=await api('/species/refine',{method:'POST',body:JSON.stringify(body)});species=result.species;remoteRevision=result.commitSha||remoteRevision;render();load(selected);status('Staging taxonomy refinement saved with identification history preserved.')}
  function createNew(){const name=prompt('New staging taxon or useful group name:');if(!name)return;const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'taxonomy',id='stg-'+slug+'-'+crypto.randomUUID().slice(0,8),at=new Date().toISOString(),historyId=id+'-ident-'+crypto.randomUUID();species.unshift({id,name,scientificName:'',rank:'unresolved taxon',category:'Wildlife',icon:'🐾',status:'draft',aliases:[],summary:'',story:'',hero:'',parentSpeciesId:null,mergedFrom:[],mergedInto:null,redirectAliases:[],identification:{acceptedIdentificationId:historyId,acceptedLabel:name,confidence:'unidentified',history:[{id:historyId,label:name,scientificName:'',rank:'unresolved taxon',confidence:'unidentified',source:'Human-created staging acceptance record',sourceObservationId:null,note:'',at,status:'accepted'}]},public:false,createdAt:at,updatedAt:at});selected=id;render();load(id);status('Staging draft created locally. Save refinement to write it.')}
  e.search.oninput=render;e.form.onsubmit=event=>refine(event).catch(error=>status(error.message,true));
  $('#mergeButton').onclick=()=>status('Taxonomy merges require a separate Historical Curator decision and are blocked.',true);
  $('#refresh').onclick=()=>refresh().catch(error=>status(error.message,true));$('#newSpecies').onclick=createNew;
  render();if(e.key.value)refresh().catch(error=>status(error.message,true));
})();
