const json=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json',...h}});
function cors(env,req){const origin=req.headers.get('origin')||'';const allowed=(env.ALLOWED_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean);const ok=!origin||allowed.includes(origin);return {'access-control-allow-origin':ok?origin:(allowed[0]||'null'),'vary':'Origin','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,OPTIONS'};}
async function gh(env,path,init={}){const r=await fetch(`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${path}`,{...init,headers:{accept:'application/vnd.github+json',authorization:`Bearer ${env.GITHUB_TOKEN}`,'x-github-api-version':'2022-11-28','user-agent':'pollinator-garden-brain',...(init.headers||{})}});if(!r.ok&&r.status!==404)throw Error(`GitHub ${r.status}: ${await r.text()}`);return r;}
const b64utf8=s=>btoa(unescape(encodeURIComponent(s)));const utf8b64=s=>decodeURIComponent(escape(atob(s)));
async function getFile(env,path){const r=await gh(env,path);if(r.status===404)return {sha:null,text:null};const j=await r.json();return {sha:j.sha,text:utf8b64(j.content.replace(/\n/g,''))};}
async function putText(env,path,text,message){const old=await getFile(env,path);const body={message,content:b64utf8(text),branch:env.GITHUB_BRANCH||'main'};if(old.sha)body.sha=old.sha;const r=await gh(env,path,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json();}
async function putBase64(env,path,content,message){const old=await getFile(env,path);const body={message,content,branch:env.GITHUB_BRANCH||'main'};if(old.sha)body.sha=old.sha;const r=await gh(env,path,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json();}
function safe(x){return String(x||'entry').toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'entry';}
function auth(req,env){return req.headers.get('authorization')===`Bearer ${env.NOTEBOOK_KEY}`;}
function validatePlacements(p){if(!Array.isArray(p)||p.length>1000)throw Error('Invalid placements payload');for(const x of p){if(!x||!x.id||!['plant','object'].includes(x.kind)||!x.map||typeof x.x!=='number'||typeof x.y!=='number'||x.x<0||x.x>100||x.y<0||x.y>100)throw Error(`Invalid placement: ${x?.id||'unknown'}`);}}
export default {async fetch(req,env){const h=cors(env,req);if(req.method==='OPTIONS')return new Response(null,{headers:h});const url=new URL(req.url);if(url.pathname==='/health'&&req.method==='GET')return json({ok:true,service:'Pollinator Path Garden Brain'},200,h);if(!auth(req,env))return json({error:'Unauthorized'},401,h);
try{
if(url.pathname==='/placements'&&req.method==='POST'){const body=await req.json();validatePlacements(body.placements);const text=`// Automatically published by the Garden Map Editor.\nwindow.GARDEN_PLACEMENTS = ${JSON.stringify(body.placements,null,2)};\nwindow.GARDEN_BRAIN.placements = window.GARDEN_PLACEMENTS;\n`;await putText(env,'placements.js',text,'Garden Brain: publish map placements');return json({ok:true,count:body.placements.length},200,h);}
if(url.pathname==='/entry'&&req.method==='POST'){const e=await req.json();if(!e.id||!e.date)throw Error('Missing entry id or date');if((e.photos||[]).length>20)throw Error('Maximum 20 photos per entry');let files=0;const photoPaths=[];for(let i=0;i<(e.photos||[]).length;i++){const p=e.photos[i];const raw=String(p.data||'').split(',')[1];if(!raw)continue;if(raw.length>12_000_000)throw Error('A prepared photo is too large');const primary=e.primary||{};let folder=`images/observations/${e.date.slice(0,4)}/${safe(e.id)}`;if(p.hero&&primary.kind==='plant')folder=`images/plants/${safe(primary.id)}`;if(p.hero&&primary.kind==='visitor')folder=`images/wildlife/${safe(primary.id)}`;const name=p.hero?'hero.jpg':safe(p.name||`${e.date}-${i+1}.jpg`);const path=`${folder}/${name}`;await putBase64(env,path,raw,`Field notebook: add ${e.title||e.id}`);photoPaths.push(path);files++;}
const current=await getFile(env,'observations.js');let arr=[];if(current.text){const match=current.text.match(/window\.OBSERVATIONS\s*=\s*([\s\S]*);\s*$/);if(match)arr=JSON.parse(match[1]);}const clean={...e,photos:photoPaths};delete clean.setHero;delete clean.privateNotes;arr=arr.filter(x=>x.id!==clean.id);arr.unshift(clean);await putText(env,'observations.js','window.OBSERVATIONS = '+JSON.stringify(arr,null,2)+';\n',`Field notebook: ${e.title||e.id}`);files++;return json({ok:true,files},200,h);}
return json({error:'Not found'},404,h);
}catch(err){return json({error:err.message},500,h);}}};
