const json=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json',...h}});
function cors(env){return {'access-control-allow-origin':env.ALLOWED_ORIGIN||'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'POST,OPTIONS'};}
async function gh(env,path,init={}){const r=await fetch(`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${path}`,{...init,headers:{'accept':'application/vnd.github+json','authorization':`Bearer ${env.GITHUB_TOKEN}`,'x-github-api-version':'2022-11-28','user-agent':'pollinator-field-notebook',...(init.headers||{})}});if(!r.ok&&r.status!==404)throw Error(`GitHub ${r.status}: ${await r.text()}`);return r;}
const b64utf8=s=>btoa(unescape(encodeURIComponent(s))); const utf8b64=s=>decodeURIComponent(escape(atob(s)));
async function getFile(env,path){const r=await gh(env,path);if(r.status===404)return {sha:null,text:null};const j=await r.json();return {sha:j.sha,text:utf8b64(j.content.replace(/\n/g,''))};}
async function put(env,path,content,message){const old=await getFile(env,path);const body={message,content,branch:env.GITHUB_BRANCH||'main'};if(old.sha)body.sha=old.sha;const r=await gh(env,path,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json();}
function safe(x){return String(x||'entry').toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'entry';}
export default {async fetch(req,env){const h=cors(env);if(req.method==='OPTIONS')return new Response(null,{headers:h});if(new URL(req.url).pathname!='/entry'||req.method!=='POST')return json({error:'Not found'},404,h);if(req.headers.get('authorization')!==`Bearer ${env.NOTEBOOK_KEY}`)return json({error:'Unauthorized'},401,h);try{const e=await req.json();if(!e.id||!e.date)throw Error('Missing entry id or date');let files=0;const photoPaths=[];for(let i=0;i<(e.photos||[]).length;i++){const p=e.photos[i];const raw=String(p.data||'').split(',')[1];if(!raw)continue;const primary=e.primary||{};let folder='images/observations/'+e.date.slice(0,4)+'/'+safe(e.id);if(p.hero&&primary.kind==='plant')folder=`images/plants/${safe(primary.id)}`;if(p.hero&&primary.kind==='visitor')folder=`images/wildlife/${safe(primary.id)}`;const name=p.hero?'hero.jpg':safe(p.name||`${e.date}-${i+1}.jpg`);const path=`${folder}/${name}`;await put(env,path,raw,`Field notebook: add ${e.title||e.id}`);photoPaths.push(path);files++;}
const current=await getFile(env,'observations.js');let arr=[];if(current.text){const match=current.text.match(/window\.OBSERVATIONS\s*=\s*([\s\S]*);\s*$/);if(match)arr=JSON.parse(match[1]);}const clean={...e,photos:photoPaths};delete clean.setHero;arr=arr.filter(x=>x.id!==clean.id);arr.unshift(clean);await put(env,'observations.js',b64utf8('window.OBSERVATIONS = '+JSON.stringify(arr,null,2)+';\n'),`Field notebook: ${e.title||e.id}`);files++;
return json({ok:true,files},200,h);}catch(err){return json({error:err.message},500,h);}}};